---
title: "Slides and Data"
---

Throughout this course we will have in-class mini-assignments embedded in the slides.

Answers to the mini-assignments will be available after the Lab :)

## Slides

```{r, include = FALSE}

### First compiles slides in _labs/0_RUN.R

after_date <- 1
f <- "slides"


library(tidyverse)
library(glue)
library(magrittr)

file.copy(c("_labs/pres_styles.css", 
            "_labs/global_styles.css",
            "_labs/macros.js",
            "_labs/figures"), f, recursive = TRUE)

labs <- tribble(
  ~f,                         ~nice,                                 ~answers,
  "1_intro_to_R.Rmd",         "1 Introduction to R",                 TRUE,
  "2_loading_and_figs.Rmd",   "2 Loading Data and Creating Figures", TRUE,
  "3_data_exploration.Rmd",   "3 Data Exploration",                  TRUE,
  "4_regression_anova.Rmd",   "4 Regressions and ANOVAs",            TRUE,
  "5_advanced_models.Rmd",    "5 Interactions and Post-Hoc tests",   TRUE,
  "6_glm_non_parametric.Rmd", "6 GLMs and Non-parametric stats",     TRUE) %>%
  mutate(f = file.path("./_labs", f),
         nice = file.path(nice))
```

```{r getdata, include = FALSE}
# MOVE SLIDES

if(dir.exists(dirname(f)) && !dir.exists(f)) dir.create(f)

# MOVE BEFORE PDF
before <- list.files(path = "_labs/Handouts", full.names = TRUE) %>%
  str_subset("answers", negate = TRUE) %T>%
  file.copy(f, overwrite = TRUE)

# MOVE BEFORE HTML
list.files(path = "_labs",  full.names = TRUE,
           pattern = paste0(str_remove_all(before, "_labs/Handouts/|.pdf"),
                            collapse = "|")) %>%
  str_subset("pdf|answers", negate = TRUE) %>%
  file.copy(f, overwrite = TRUE, recursive = TRUE)

# MOVE AFTER PDF/HTML
if(length(after_date) > 0){
  
  # PDF
  after <- list.files(path = "_labs/Handouts", pattern = ".pdf", full.names = TRUE) %>%
    str_subset("answers") %>%
    str_subset(glue_collapse(glue("_labs/Handouts/{after_date} "), sep = "|"))
  file.copy(after, f, overwrite = TRUE)
  
  # HTML
  list.files(path = "_labs",  full.names = TRUE,
             pattern = str_remove_all(after, "_labs/Handouts/|.pdf")) %>%
    str_subset("pdf", negate = TRUE) %>%
    file.copy(f, overwrite = TRUE, recursive = TRUE)
}

slides <- tibble(file = list.files("./slides", full.names = TRUE),
                 name = basename(file)) %>%
  filter(!str_detect(file, "_files|.css|.js|figures")) %>%
  mutate(name = str_remove_all(name, ".html|.pdf|-print| - answers"),
         type = str_extract(file, "pdf|html"),
         answers = if_else(str_detect(file, "answers"), "answers", "normal")) %>%
  arrange(file)


text <- slides %>%
  complete(type = c("html", "pdf"), answers = c("normal", "answers"), 
           nesting(name = labs$nice)) %>%
  mutate(file = replace_na(file, ""),
         title = glue("**{str_replace(name, '^([0-9]{1})', '\\\\1.')}**"),
         answers = if_else(answers == "normal", "", " - answers"),
         type = glue("{type}{answers}"),
         nolinks = case_when(file != "" ~ glue("({type})"),
                             TRUE ~ glue("({type})")),
         links = case_when(file != "" ~ glue("([{type}]({file}))"),
                           TRUE ~ glue("({type})"))) %>%
  arrange(name, type) %>%
  group_by(name) %>%
  summarize(links = glue_collapse(links, sep = "|"),
            nolinks = glue_collapse(nolinks, sep = "|"),
            title_nolinks = glue("{title[1]}{nolinks}"),
            title = glue("{title[1]} {links}"), .groups = "drop") %>%
  arrange(title)
```


```{r, echo = FALSE, message = FALSE, results = "asis"}

#for(n in seq_along(text$title_nolinks)) cat(text$title_nolinks[n], "\n\n", sep = "")
for(n in seq_along(text$title)) cat(text$title[n], "\n\n", sep = "")
```

